"use client";

import { useEffect, useMemo, useState } from "react";
import { Camera, Filter, MessageCircle, Send } from "lucide-react";
import { Alert, Box, Button, Card, CardBody, EmptyState, Flex, PageHeader, SearchInput, Skeleton, StatusBadge, Text } from "@/lib/design-system";
import { getStoredSession } from "@/lib/auth-session";
import { listInstagramAccounts, listInstagramComments, type InstagramComment } from "@/lib/api-client";

export default function InstagramCommentsPage() {
  const [comments, setComments] = useState<InstagramComment[]>([]); const [connected, setConnected] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [query, setQuery] = useState(""); const [filter, setFilter] = useState<"ALL" | "NEW" | "READ">("ALL"); const [cursor, setCursor] = useState<string | null>(null);
  useEffect(() => { void load(); }, []);
  async function load(next?: string, status: "ALL" | "NEW" | "READ" = filter) { const session = getStoredSession(); if (!session?.accessToken) return; try { setLoading(true); const accounts = await listInstagramAccounts(session.accessToken); setConnected(accounts.accounts.length > 0); if (!accounts.accounts.length) return; const result = await listInstagramComments({ accessToken: session.accessToken, limit: 20, ...(next ? { cursor: next } : {}), ...(status === "ALL" ? {} : { status }) }); setComments((previous) => next ? [...previous, ...result.comments] : result.comments); setCursor(result.nextCursor ?? null); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível carregar os comentários."); } finally { setLoading(false); } }
  const filtered = useMemo(() => comments.filter((item) => `${item.author.username ?? ""} ${item.text ?? ""}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())), [comments, query]); const unread = comments.filter((item) => item.status === "NEW").length;
  return <Box css={{ maxW: "1160px", mx: "auto" }}><PageHeader eyebrow="Instagram" title="Comentários" description="Acompanhe interações recentes e priorize o que precisa da sua atenção." actions={<Button variant="outline" size="sm" disabled><Send size={15} />Responder em breve</Button>} />{error && <Alert tone="error" dismissible onClose={() => setError(null)} mb={5}>{error}</Alert>}
    {!loading && !connected ? <EmptyState title="Conecte o Instagram para começar" description="Os comentários de uma conta profissional aparecerão organizados aqui." action={{ label: "Conectar Instagram", onClick: () => { window.location.href = "/settings/integrations"; } }} size="md" /> : <><Card variant="default" padding="sm"><CardBody css={{ p: 3 }}><Flex css={{ gap: 3, flexWrap: "wrap", alignItems: "center" }}><Box css={{ flex: "1 1 240px" }}><SearchInput value={query} onChange={setQuery} placeholder="Buscar por autor ou comentário" /></Box><Flex css={{ gap: 1, flexWrap: "wrap", alignItems: "center" }}><Filter size={15} />{(["ALL", "NEW", "READ"] as const).map((item) => <Button key={item} size="sm" variant={filter === item ? "solid" : "ghost"} onClick={() => { setFilter(item); setComments([]); setCursor(null); void load(undefined, item); }}>{item === "ALL" ? `Todos (${comments.length})` : item === "NEW" ? `Novos (${unread})` : "Lidos"}</Button>)}</Flex></Flex></CardBody></Card>
      <Box css={{ mt: 5, bg: "surface.primary", border: "1px solid", borderColor: "surface.border", borderRadius: "lg", overflow: "hidden" }}>{loading && !comments.length ? Array.from({ length: 5 }, (_, index) => <Skeleton key={index} height="104px" />) : filtered.length ? filtered.map((comment) => <CommentRow key={comment.id} comment={comment} />) : <EmptyState title="Nenhum comentário encontrado" description="Ajuste a busca ou os filtros para visualizar outras interações." size="sm" />}</Box>{cursor && <Flex css={{ justifyContent: "center", mt: 5 }}><Button variant="outline" loading={loading} onClick={() => void load(cursor)}>Carregar mais</Button></Flex>}</>}</Box>;
}

function CommentRow({ comment }: { comment: InstagramComment }) { const date = new Intl.DateTimeFormat("pt-BR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(comment.createdAt)); return <Flex css={{ gap: 3, p: 4, alignItems: "flex-start", borderBottom: "1px solid", borderColor: "surface.border", _last: { borderBottom: 0 }, _hover: { bg: "surface.secondary" } }}><Box css={{ display: "grid", placeItems: "center", w: 8, h: 8, borderRadius: "full", flexShrink: 0, bg: "surface.tertiary", color: "text.secondary" }}><Camera size={15} /></Box><Box css={{ flex: 1, minW: 0 }}><Flex css={{ justifyContent: "space-between", gap: 3, flexWrap: "wrap" }}><Box><Flex css={{ gap: 2, alignItems: "center" }}><Text css={{ fontWeight: "medium", fontSize: "sm" }}>@{comment.author.username ?? "cliente"}</Text>{comment.status === "NEW" && <StatusBadge status="new" />}</Flex><Text css={{ mt: 1, fontSize: "xs", color: "text.tertiary" }}>{date}</Text></Box><Button aria-label="Responder em breve" variant="ghost" size="sm" disabled><MessageCircle size={16} /></Button></Flex><Text css={{ mt: 3, fontSize: "sm", color: "text.secondary", lineHeight: "relaxed", whiteSpace: "pre-wrap" }}>{comment.text ?? "Comentário sem conteúdo de texto."}</Text><Text css={{ mt: 2, fontSize: "xs", color: "text.quaternary" }}>Instagram · Publicação</Text></Box></Flex>; }
